name: Installation / Brew Issue
description: Report a failure to install a formula via Homebrew
title: "[Install]: "
labels: ["installation"]
assignees: ["jacksonfergusondev"]
body:
  - type: markdown
    attributes:
      value: |
        **Use this specifically for `brew install` failures.** If the tool is already installed but is behaving incorrectly, please file the issue on the specific tool's repository:
        - [Git Pulsar Issues](https://github.com/jacksonfergusondev/git-pulsar/issues)
        - [Protostar Issues](https://github.com/jacksonfergusondev/protostar/issues)
  - type: dropdown
    id: formula
    attributes:
      label: Affected Formula
      description: Which tool failed to install?
      options:
        - git-pulsar
        - protostar
    validations:
      required: true
  - type: textarea
    id: brew-config
    attributes:
      label: Homebrew Config
      description: Please run `brew config` and paste the output below.
      render: bash
    validations:
      required: true
  - type: textarea
    id: failure-log
    attributes:
      label: Failure Output
      description: |
        Please run the installation with the verbose flag and paste the failure log.
        Example: `brew install <formula> --verbose`
      render: bash
    validations:
      required: true
