name: Installation / Brew Issue
description: Report a failure to install git-pulsar via Homebrew
title: "[Install]: "
labels: ["installation"]
assignees: ["jacksonferguson"]
body:
  - type: markdown
    attributes:
      value: |
        **Use this specifically for `brew install` failures.**
        If the application is installed but crashing or behaving weirdly, please file an issue on the main repository: https://github.com/jacksonferguson/git-pulsar/issues
  - type: textarea
    id: brew-config
    attributes:
      label: Homebrew Config
      description: Please run `brew config` and paste the output below.
      render: bash
    validations:
      required: true
  - type: textarea
    id: failure-log
    attributes:
      label: Failure Output
      description: Please run `brew install git-pulsar --verbose` and paste the failure log below.
      render: bash
    validations:
      required: true