class Focal < Formula
  include Language::Python::Virtualenv

  desc "CLI utilities for AI-assisted development context and workflow automation"
  homepage "https://github.com/jacksonfergusondev/focal"
  url "https://github.com/jacksonfergusondev/focal/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "REPLACE_WITH_ACTUAL_SHA256"
  license "MIT"

  depends_on "ast-grep"
  depends_on "bat"
  depends_on "fd"
  depends_on "fzf"
  depends_on "gh"
  depends_on "python@3.13"
  depends_on "ripgrep"

  # --- AUTOGENERATED_RESOURCES_START ---
  # --- AUTOGENERATED_RESOURCES_END ---

  def install
    # Install bash architecture
    prefix.install "bin", "lib", "libexec", "focal"

    # Create virtualenv and install external resources only
    venv = virtualenv_create(prefix/"libexec", "python3.13")
    venv.pip_install resources
  end

  test do
    system bin/"focal", "--help"
  end
end
